### ISSUE TITLE
cant find logs on run

### ISSUE THREAD

**Issue by shavo007** [buildkite-plugins/docker-compose-buildkite-plugin#247] opened 2019-11-27 22:40 UTC
I have an issue on buildkite running tests with docker compose plugin.

I need to view the logs for all containers to see whats going on

```
  - label: ':jest: Run Local E2E'
    timeout_in_minutes: 15
    agents:
      queue: 'agent:cicd'
    plugins:
      <<: *npm-login
      docker-compose#v3.1.0:
        run: e2e
        upload-container-logs: always
```

I do not see any logs uploaded as artifacts. Is there something else i need to do?

Thanks,
Shane

**Comment by shavo007** [comment] 2019-12-02 01:13
<img width="1125" alt="Screenshot 2019-12-02 at 12 12 51" src="https://user-images.githubusercontent.com/5466825/69924030-31064f80-14fd-11ea-9ba3-d58e216d9c76.png">

**Comment by shavo007** [comment] 2019-12-02 01:14
it doesnt look like it gets as far as uploading the logs as an artifact

https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/commands/run.sh#L297

**Comment by levicole** [comment] 2020-01-08 15:52
@shavo007 if you've not figured it out yet, in 3.1.0, `upload-container-logs` is broken. We pointed ours at master and all is well.

Should be able to change:

```
docker-compose#v3.1.0:
```

to

```
docker-compose#master:
```

until a new release is cut.

**Comment by Sushisource** [comment] 2021-09-21 23:02
Does this still not work? I'm using `3.8.0` and I can't get anything to happen when I set this option

**Comment by toote** [comment] 2022-09-21 23:39
I believe that this is indeed the issue being worked on in issue #327 and related PR (#330) . As there is active work being done there I will close this one for the time being.

Duplicate of #327

**Closed by toote** 2022-09-21 23:39 UTC
