### ISSUE TITLE
Container logs not always uploading

### ISSUE THREAD

**Issue by uriahcarpenter** [buildkite-plugins/docker-compose-buildkite-plugin#118] opened 2018-04-04 18:37 UTC
When any of the compose services fail it's expected that container logs be uploaded as artifacts.

[v1.8.4](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/releases/tag/v1.8.4) fixed an issue where logs would not get uploaded.

For a docker compose build that is erroring, I reproduced the following behavior from these three versions:

v1.8.3 --> Logs not uploaded
v1.8.4 --> Logs uploaded okay
v2.0.0 --> Logs not uploaded

**Comment by lox** [comment] 2018-04-04 22:09
Sorry about this @uriahcarpenter, we'll get some tests in place to catch this regression.

**Comment by uriahcarpenter** [comment] 2018-04-04 22:45
Hi @lox. I'm no longer convinced that it's just a plain regression. Even with `v1.8.4` I don't always get logs.

[1.8.4 okay](https://buildkite.com/widen/mica/builds/36#df3c5824-1ce6-4fae-93d9-008114ee4a20)

SAME exact Git hash... but [1.8.4 with no logs](https://buildkite.com/widen/mica/builds/35#65df7661-9140-4f2e-9c0d-2e2b2de30f38)

**Comment by lox** [comment] 2018-04-04 22:54
I've suspected a race condition for container logs for a while. We'll investigate.

**Comment by toote** [comment] 2022-09-21 02:45
Given the timing, I suspect this is a duplicate of #78. Same as there, logs appear to have been running without issues for a while now so I am closing this one for the time being

**Closed by toote** 2022-09-21 02:45 UTC
