### ISSUE TITLE
Containers still running after canceled build.

### ISSUE THREAD

**Issue by andreimc** [buildkite-plugins/docker-compose-buildkite-plugin#100] opened 2018-02-14 22:02 UTC
Hey guys,

I am running build kite in kubernetes using docker in docker to run my tests and the docker compose plugin keeps the containers running on a canceled build since they don't stop that quickly.

I made my own script that seeps to have fixed the issue I do the following: docker-compose run --rm app run-specs

That ensures the linked containers die even when a build is canceled.

Would be good to have this added but I am not sure how it fit's in with your strategy

**Comment by lox** [comment] 2018-02-23 04:11
Hmmm, that is very odd, the cleanup function should fire when the script gets a `SIGQUIT`: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/hooks/commands/run.sh#L19

Is your cleanup taking longer than 10 seconds?

**Comment by shaneog** [comment] 2018-02-23 11:26
Something similar is happening to me. I'm left with many orphan networks and often (3-4 times per week) have to manually SSH into the buildkite servers to run `docker network prune` due to the 31 network limit of Docker.

**Comment by lox** [comment] 2018-03-07 08:44
If cancelling is taking longer than 10 seconds, the agent will force kill it. In the elastic stack we run `docker system prune` in cron: 

https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/conf/docker/cron.hourly/docker-gc

**Comment by lox** [comment] 2018-12-26 04:04
I'm going to close this one, as I strongly suspect it's caused by cancellation cutting off after 10 seconds. We are working on some ways to customize cancel timeouts in the agent that will make this easier.

**Closed by lox** 2018-12-26 04:04 UTC
